services:
  psql:
    image: postgres:latest
    ports:
      - "5001:5432"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.org
      PGADMIN_DEFAULT_PASSWORD: 123
    restart: unless-stopped
    depends_on:
      - psql

  users:
    image: study_ms_users
    ports:
      - "8008:8080"
    environment:
      DB_NAME: users
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: 123
      DB_ADDR: psql
    restart: unless-stopped
    depends_on:
      - psql
